{
 "title": "Op3",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "FleetView",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"FleetWiseDatabase\"",
     "measure": "Vehicle.Powertrain.Latitude",
     "rawQuery": "Select measure_value::double FROM $__database.$__table\nwhere measure_name = 'Vehicle.Powertrain.Latitude'\norder by time desc\nlimit 1",
     "table": "\"FleetWiseTable\""
    },
    {
     "database": "\"FleetWiseDatabase\"",
     "measure": "Vehicle.Powertrain.Longitude",
     "rawQuery": "select measure_value::double from FleetWiseDatabase.\"FleetWiseTable\" \nwhere measure_name = 'Vehicle.Powertrain.Longitude'\norder by time desc\nlimit 1\n",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Number of Unhealthy Vehicles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "vin100",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin101",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "expression": "$A +$B + $C +$E + $F + $G + $H + $I + $J +$K ",
     "type": "math"
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin102",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin103",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin104",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin105",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin106",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin107",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin108",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin109",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    }
   ]
  },
  {
   "title": "Number of Healthy Vehicles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "vin100",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin101",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin102",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin103",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin104",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin105",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin106",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin107",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin108",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin109",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "expression": "($A == 0)+ ($B == 0) + ($C == 0) + ($D == 0) + ($E == 0) + ($F == 0) + ($G == 0) + ($H == 0) + ($I == 0) + ($J == 0) ",
     "type": "math"
    }
   ]
  },
  {
   "title": "Fleet View",
   "type": "grafana-iot-twinmaker-sceneviewer-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "vin100",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    },
    {
     "componentName": "EVDataComp",
     "entityId": "vin101",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    }
   ]
  }
 ]
}