{
 "title": "Vehicle Inspection",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sel_entity",
    "label": "Inspection Vehicle",
    "query": {}
   },
   { "name": "sel_comp", "query": "EVDataComp" },
   {
    "name": "sel_prop",
    "query": "Vehicle_Powertrain_Battery_hasActiveDTC"
   }
  ]
 },
 "panels": [
  {
   "title": "Inspection View",
   "type": "grafana-iot-twinmaker-sceneviewer-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    }
   ]
  },
  {
   "title": "Unhealthy Vehicles",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawQuery": "SELECT distinct time, vehicleName\n    FROM \"FleetWiseDatabase\".FleetWiseTable\n    WHERE time >= ago(5m)\n    AND (measure_value::boolean) = true\n    AND measure_name = 'Vehicle.Powertrain.Battery.hasActiveDTC'\n    order by time desc\n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<center><font size=\"5\">Inspection Dashboard - ${sel_entity}</font></center>"
   },
   "targets": [
    {
     "database": "\"FleetWiseDatabase\"",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Total Operating Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "componentName": "EVDataComp", "entityId": "${sel_entity}", "properties": [ "Vehicle_TotalOperatingTime" ] }
   ]
  },
  {
   "title": "SoH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_StateOfHealth"
     ]
    }
   ]
  },
  {
   "title": "SoC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_StateOfCharge_Current"
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "componentName": "EVDataComp", "entityId": "${sel_entity}", "properties": [ "Vehicle_Speed" ] }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "componentName": "EVDataComp", "entityId": "${sel_entity}", "properties": [ "Vehicle_OutsideAirTemperature" ] }
   ]
  },
  {
   "title": "Battery Fan Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_FanRunning"
     ]
    }
   ]
  },
  {
   "title": "Max Battery Module Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_MaxTemperature"
     ]
    }
   ]
  },
  {
   "title": "DTC status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Powertrain_Battery_hasActiveDTC"
     ]
    }
   ]
  },
  {
   "title": "FL Tire Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Chassis_Axle_LeftFrontTirePressure"
     ]
    }
   ]
  },
  {
   "title": "FR Tire Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Chassis_Axle_RightFrontTirePressure"
     ]
    }
   ]
  },
  {
   "title": "BL Tire Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Chassis_Axle_LeftRearTireTemperature"
     ]
    }
   ]
  },
  {
   "title": "BR Tire Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "entityId": "${sel_entity}",
     "properties": [
      "Vehicle_Chassis_Axle_RightRearTirePressure"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "<center><font size='3'>Battery Modules Temperature & Voltage</font></center>"
   },
   "targets": [
    {
     "database": "\"FleetWiseDatabase\"",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 1 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_1_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp01'\n  AND sel_entity= '${sel_entity}'\n  AND time >= ago(15m)",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 2 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_2_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp02'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 3 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_3_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp03'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 4 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_4_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp04'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 5 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_5_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp05'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 6 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_6_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp06'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 7 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_7_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp07'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 8 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_8_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp08'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 9 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_9_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp09'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 10 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_10_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp10'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 11 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_11_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp11'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 12 Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_12_Temperature"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellTemp12'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 1 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_1_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage01'\n  AND sel_entity= '${sel_entity}'\n  AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 2 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_2_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage02'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 3 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_3_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage03'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 4 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_4_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage04'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 5 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_5_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage05'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 6 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_6_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage06'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 7 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_7_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage07'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 8  V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_8_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage08'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 9 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_9_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage09'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 10 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_10_Voltage"
     ],
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 11 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_11_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage11'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  },
  {
   "title": "Module 12 V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "componentName": "EVDataComp",
     "database": "\"FleetWiseDatabase\"",
     "entityId": "${sel_entity}",
     "measure": "Vehicle_Chassis_Axle_LeftFrontTirePressure",
     "properties": [
      "Vehicle_Powertrain_Battery_Module_12_Voltage"
     ],
     "rawQuery": "SELECT measure_value::double, time FROM $__database.$__table\nWHERE campaignName = 'fww_continuous'\n  AND measure_name = 'Vehicle_Powertrain_Battery_CellVoltage12'\n  AND sel_entity= '${sel_entity}'\n    AND time >= ago(15m)\nLIMIT 100",
     "table": "\"FleetWiseTable\""
    }
   ]
  }
 ]
}